/* 
GOOD PROMPT USED to fix the insecure code generated by BAD PROMPT:
* copy the code and Ask to Copilot (or other AI):
"What is the attack surface?"
* or Ask to Copilot:
"@workspace /fix"

! This prompt is:
A fancy way of saying:
"How might someone try to attack this project?"
And I can see that Copilot (or other AI) makes a bunch of recommendations. These include specific changes to the code, as well as certain packages that I might want to consider adding to the project to make more secure.
*/

function getProduct(product_id) {
    return db.one('SELECT * FROM products WHERE id = $1', [product_id]);
}

function search(query) {
    const searchTerm = `%${query}%`;
    return db.many(
        'SELECT * FROM products WHERE name ILIKE $1 OR description ILIKE $1',
        [searchTerm]
    );
}

function purchase(cart) {
    return db.one(
        `INSERT INTO purchases(mail, product_name, user_name, product_id, address, phone, ship_date, price)
         VALUES($1, $2, $3, $4, $5, $6, $7, $8)
         RETURNING *`,
        [
            cart.mail,
            cart.product_name,
            cart.user_name,
            cart.product_id,
            cart.address,
            cart.phone,
            cart.ship_date,
            cart.price
        ]
    );
}

function get_purchased(username) {
    return db.many('SELECT * FROM purchases WHERE user_name = $1', [username]);
}

var actions = {
    "list": list_products,
    "getProduct": getProduct,
    "search": search,
    "purchase": purchase,
    "getPurchased": get_purchased
};

module.exports = actions;